services:
  qinglong:
    image: whyour/qinglong:2.20.2
    networks:
      - acepanel-network
    volumes:
      - ./data:/ql/data
    ports:
      - "${QINGLONG_PORT_HTTP}:5700"
    healthcheck:
      test: [ "CMD-SHELL", "curl -fsSL http://localhost:5700 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
networks:
  acepanel-network:
    external: true
