services:
  redis:
    image: redis:8.6.1-alpine
    restart: unless-stopped
    networks:
      - acepanel-network
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server /etc/redis/redis.conf ${REDIS_REDIS_ROOT_PASSWORD:+--requirepass "${REDIS_REDIS_ROOT_PASSWORD}"}
    volumes:
      - ./data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
      - ./logs:/logs
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
networks:
  acepanel-network:
    external: true