name: Sync
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
concurrency:
  group: sync
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          cache: true
          go-version: 'stable'
      - name: Sync to API
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          go run main.go
